# Generated by Django 4.1 on 2023-01-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('origin', models.CharField(default='', max_length=100)),
                ('weight', models.IntegerField(default=0)),
                ('method', models.CharField(default='', max_length=100)),
                ('images', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
