# Generated by Django 4.1 on 2023-01-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_product_coffee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_coffee',
            name='name',
        ),
    ]
